Repository replikation/What_the_Phage, pull requests merged in 2020-10, with the labels that each got.

#108 Integration virsorter 2
  README.md
  configs/container.config
  modules/parser/filter_virsorter2.nf
  modules/raw_data_collection/virsorter2_collect_data.nf
  modules/tools/virsorter2.nf
  modules/upsetr.nf
  nextflow.config
  phage.nf
Labels: enhancement

#109 Seeker integration
  Docs/Citations.txt
  README.md
  configs/container.config
  configs/local.config
  configs/node.config
  docs/Citations.bib
  modules/parser/filter_seeker.nf
  modules/tools/seeker.nf
  nextflow.config
  phage-tool-Dockerfiles/seeker/Dockerfile
  phage.nf
Labels: Priority MEDIUM, enhancement

#111 Seeker optimization
  configs/container.config
  modules/fastqTofasta.nf
  modules/hmmscan.nf
  modules/input_suffix_check.nf
  modules/normalize_contig_size.nf
  modules/parser/chromomap_parser.nf
  modules/parser/filter_PPRmeta.nf
  modules/parser/filter_deepvirfinder.nf
  modules/parser/filter_marvel.nf
  modules/parser/filter_metaphinder.nf
  modules/parser/filter_seeker.nf
  modules/parser/filter_sourmash.nf
  modules/parser/filter_tool_names.nf
  modules/parser/filter_vibrant.nf
  modules/parser/filter_virfinder.nf
  modules/parser/filter_virnet.nf
  modules/parser/filter_virsorter.nf
  modules/parser/parse_reads.nf
  modules/prodigal.nf
  modules/r_plot.nf
  modules/r_plot_reads.nf
  modules/raw_data_collection/deepvirfinder_collect_data.nf
  modules/raw_data_collection/marvel_collect_data.nf
  modules/raw_data_collection/metaphinder_collect_data.nf
  modules/raw_data_collection/pprmeta_collect_data.nf
  modules/raw_data_collection/seeker_collect_data.nf
  modules/raw_data_collection/sourmash_collect_data.nf
  modules/raw_data_collection/vibrant_collect_data.nf
  modules/raw_data_collection/virfinder_collect_data.nf
  modules/raw_data_collection/virnet_collect_data.nf
  modules/raw_data_collection/virsorter_collect_data.nf
  modules/removeSmallReads.nf
  modules/tools/deepvirfinder.nf
  modules/tools/marvel.nf
  modules/tools/metaphinder.nf
  modules/tools/pprmeta.nf
  modules/tools/seeker.nf
  modules/tools/sourmash.nf
  modules/tools/vibrant.nf
  modules/tools/virfinder.nf
  modules/tools/virnet.nf
  modules/tools/virsorter.nf
  nextflow.config
  phage.nf
Labels: Priority HIGH
