Repository replikation/What_the_Phage, pull requests merged in 2020-07, with the labels that each got.

#83 Heatmap size fix
  bin/convert.sh
  bin/heatmap.R
  configs/container.config
  modules/parser/filter_metaphinder.nf
  modules/parser/filter_virnet.nf
  modules/r_plot.nf
  modules/testprofile.nf
  nextflow.config
  phage.nf
Labels: enhancement

#84 slurm inclusion
  configs/container.config
  configs/node.config
  modules/databases/download_checkV_DB.nf
  modules/databases/download_pvog_DB.nf
  modules/databases/download_references.nf
  modules/databases/download_rvdb_DB.nf
  modules/databases/download_vog_DB.nf
  modules/databases/phage_references_blastDB.nf
  modules/databases/ppr_download_dependencies.nf
  modules/databases/sourmash_download_DB.nf
  modules/databases/vibrant_download_DB.nf
  modules/databases/virsorter_download_DB.nf
  modules/setup_container.nf
  modules/tools/metaphinder.nf
  nextflow.config
  phage.nf
Labels: Priority MEDIUM, enhancement

#85 Testing virome flag
  bin/heatmap.R
  modules/parser/filter_deepvirfinder.nf
  modules/parser/filter_metaphinder.nf
  modules/parser/filter_vibrant.nf
  modules/parser/filter_virfinder.nf
  modules/parser/filter_virnet.nf
  modules/parser/filter_virsorter.nf
  modules/raw_data_collection/vibrant_collect_data.nf
  modules/raw_data_collection/virsorter_collect_data.nf
  modules/tools/sourmash.nf
  modules/tools/vibrant.nf
  modules/tools/virsorter.nf
  nextflow.config
  phage.nf
Labels: Priority HIGH, enhancement

#87 upgrade sourmash to 3.4.1, use zipped databases
  configs/container.config
  modules/databases/sourmash_download_DB.nf
  modules/sourmash_for_tax.nf
  modules/tools/sourmash.nf
  phage.nf
Labels: enhancement
